version: '3'
services:
  app:
    image: "ttree/flowapp:7.2"
    restart: always
    ports:
      - "2015:2015"
    # user: 1000:1000
    environment: 
      - FLOW_CONTEXT=Development
      - FLOWAPP_CONTEXT=Development
    # volumes: 
    #   - .:/data
    networks:
      - backend
    depends_on:
      - db
  db:
    image: "mariadb:10.4.2"
    restart: on-failure
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=neos
      - MYSQL_DATABASE=neos
    networks:
      - backend
networks:
  backend: